Repository mfem/web, pull requests merged in 2020-06, with the labels that each got.

#56 Quick fix of periodic mesh example [per-mesh-dev]
  src/mesh-format-v1.x.md
Labels: bug, ready-for-review

#58 Improved example filtering
  README.md
  src/examples.md
Labels: ready-for-review

#61 adding new LF
  src/lininteg.md
Labels: ready-for-review

#63 Added an MRI image to the Gallery
  src/gallery.md
  src/img/gallery/mri-full.png
  src/img/gallery/mri.png
Labels: gallery, ready-for-review

#57 Navier miniapp description
  README.md
  src/examples.md
  src/img/examples/navier_shear4.png
Labels: ready-for-review

#66 Added MFEM video link
  src/index.md
  src/news.md
Labels: news
