Repository mfem/web, pull requests merged in 2020-10, with the labels that each got.

#59 Fluids / Navier extended documentation
  mkdocs.yml
  src/fluids.md
  src/index.md
Labels: examples, ready-for-review

#81 Updated publications.
  src/publications.md
Labels: WIP

#35 [WIP] Draft for adding documentation of nonlinear integrators
  src/fem.md
  src/nonlininteg.md
Labels: WIP, enhancement

#83 Changes for mfem-4.2
  export.sh
  src/about.md
  src/download.md
  src/features.md
  src/index.md
Labels: release
