Repository mfem/web, pull requests merged in 2021-11, with the labels that each got.

#148 Documentation for Example 30
  src/examples.md
  src/features.md
  src/img/examples/ex30.png
Labels: ready-for-review

#140 Autodiff
  mkdocs.yml
  src/autodiff.md
  src/electromagnetics.md
  src/fluids.md
  src/getting-started.md
  src/meshing-miniapps.md
Labels: enhancement, WIP, miniapps

#151 Added a page for MFEM-related videos
  mkdocs.yml
  src/index.md
  src/news.md
  src/videos.md
  src/workshop.md
  template/js/base.js
Labels: enhancement
