Repository mfem/web, pull requests merged in 2021-03, with the labels that each got.

#91 Update of publications for 2021.
  src/about.md
  src/publications.md
Labels: update

#95 Add picture and description for ex28(p)
  src/examples.md
  src/features.md
  src/img/examples/ex28.png
Labels: examples

#97 Info about the distance solver.
  src/examples.md
  src/features.md
  src/img/examples/distance.png
  src/news.md
  src/publications.md
Labels: ready-for-review
