Repository mfem/web, pull requests merged in 2021-04, with the labels that each got.

#100 Fix the tags to correctly display search results
  src/examples.md
Labels: bug, ready-for-review

#101 Adding documentation for overlapping grids miniapps
  src/examples.md
  src/features.md
  src/img/examples/overlapping.png
Labels: ready-for-review

#102 Documentation for Block Solvers miniapp
  src/examples.md
  src/img/examples/block-solvers.png
Labels: ready-for-review

#108 corrected ex27 categories
  src/examples.md
Labels: ready-for-review

#111 Adding documentation for ex29 [ex29-doc]
  src/examples.md
  src/features.md
  src/img/examples/ex29.png
Labels: enhancement, examples
