Repository mfem/web, pull requests merged in 2021-07, with the labels that each got.

#120 Small changes to align with newer markdown version
  README.md
  src/examples.md
  src/publications.md
Labels: building, enhancement, publications

#121 MFEM Community Workshop
  src/index.md
  src/news.md
  src/workshop.md
Labels: news

#117 Minor fixes in fluids.md
  src/fluids.md
Labels: bug, miniapps, minor

#122 Fix links to GLVis.com/live visualizations
  src/examples.md
  src/meshing.md
  src/toys.md
Labels: bug

#110 Website changes for mfem-4.3
  src/download.md
  src/index.md
  src/news.md
Labels: release
