Repository mfem/web, pull requests merged in 2023-09, with the labels that each got.

#226 Add documentation for the SPDE mini app
  src/examples.md
  src/features.md
  src/img/examples/spde.png
Labels: ready-for-review, miniapps

#229 Highlighted workshop on homepage
  src/img/seminar/southworth.jpg
  src/index.md
  src/seminar.md
Labels: ready-for-review

#228 Topology optimization
  src/examples.md
  src/features.md
  src/img/examples/ex37.png
Labels: ready-for-review, examples

#230 Website changes for MFEM v4.6
  src/about.md
  src/download.md
  src/index.md
  src/news.md
  src/publications.md
Labels: release
