Repository mfem/web, pull requests merged in 2025-04, with the labels that each got.

#316 Laplace \mapsto Poisson
  src/examples.md
  src/features.md
  src/mesh-format-v1.x.md
  src/nurbs.md
  src/publications.md
  src/serial-tutorial.md
  src/tutorial/fem.md
  src/tutorial/further.md
  src/videos.md
Labels: ready-for-review

#308 Website changes for MFEM v4.8
  src/about.md
  src/download.md
  src/electromagnetics.tex
  src/examples.md
  src/features.md
  src/img/examples/spiral.mp4
  src/index.md
  src/mesh-format-v1.x.md
  src/news.md
  src/nurbs.md
  src/publications.md
  src/serial-tutorial.md
  src/toys.md
  src/tutorial/fem.md
  src/tutorial/further.md
  src/videos.md
Labels: release

#321 2025 MFEM Workshop
  mkdocs.yml
  src/img/psu_campus_map_smsu.png
  src/index.md
  src/news.md
  src/workshop.md
  src/workshop24.md
Labels: WIP, workshop
